// Bakes the New Jersey map used by the promo into promo/map-data.js so the page
// works offline. Uses the same packages and projection as the demo app.
//   node promo/tools/build-map.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { geoContains, geoMercator, geoPath } from 'd3-geo';
import { feature, mesh } from 'topojson-client';

const require = createRequire(import.meta.url);
const atlas = JSON.parse(readFileSync(require.resolve('us-atlas/counties-10m.json'), 'utf8'));
const state = atlas.objects.states.geometries.find((g) => String(g.id).padStart(2, '0') === '34');
const counties = atlas.objects.counties.geometries.filter((g) => String(g.id).padStart(5, '0').startsWith('34'));
const nj = feature(atlas, state);
const W = 520, H = 760;
const projection = geoMercator().fitExtent([[26, 22], [W - 26, H - 22]], nj);
const path = geoPath(projection);
const round = (d) => d.replace(/(\d+\.\d{1})\d+/g, '$1');

// The nine fictional demo companies (demo/src/components/apps/Gauge/gauge-data.ts).
const src = readFileSync(new URL('../../demo/src/components/apps/Gauge/gauge-data.ts', import.meta.url), 'utf8');
const companies = [...src.matchAll(/id: '(\w+)', name: '([^']+)', town: '([^']+)', county: '([^']+)', sector: '([^']+)', year: (\d+),\s*coordinates: \[([-\d.]+), ([-\d.]+)\], funded: (\w+), tier: '([^']+)', signal: '([^']+)', raised: '([^']+)',\s*description: '([^']+)'/g)]
  .map((m) => ({
    id: m[1], name: m[2], town: m[3], county: m[4], sector: m[5], year: +m[6],
    lon: +m[7], lat: +m[8], funded: m[9] === 'true', tier: m[10], signal: m[11], raised: m[12], description: m[13],
    xy: projection([+m[7], +m[8]]).map((v) => +v.toFixed(1)),
  }));
// Evidence, unknowns, and program flags from each company's block.
const blocks = src.split(/\n\t\{\n/).slice(1);
for (const c of companies) {
  const block = blocks.find((b) => b.includes(`id: '${c.id}'`));
  const list = (key) => [...(block.match(new RegExp(`${key}: \\[([^\\]]*)\\]`))?.[1] ?? '').matchAll(/'([^']+)'/g)].map((m) => m[1]);
  c.evidence = list('evidence');
  c.unknowns = list('unknowns');
  const flags = block.match(/standardPrograms\((\w+), (\w+)\)/);
  c.sbir = flags?.[1] === 'true';
  c.lifeScience = flags?.[2] === 'true';
}
if (companies.length !== 9) throw new Error(`expected 9 demo companies, parsed ${companies.length}`);

// Deterministic "other public signal" dots inside the state for the 118-signal reveal.
let seed = 1435;
const rand = () => ((seed = (seed * 16807) % 2147483647) / 2147483647);
const [[x0, y0], [x1, y1]] = path.bounds(nj);
const extra = [];
while (extra.length < 109) {
  const p = [x0 + rand() * (x1 - x0), y0 + rand() * (y1 - y0)];
  const ll = projection.invert(p);
  // Weight toward the northeast corridor where most signals are.
  const corridor = ll[1] > 40.1 ? 1 : 0.35;
  if (geoContains(nj, ll) && rand() < corridor) extra.push({ xy: p.map((v) => +v.toFixed(1)), funded: rand() < 0.3 });
}

const data = {
  width: W, height: H,
  state: round(path(nj)),
  counties: round(path(mesh(atlas, { type: 'GeometryCollection', geometries: counties }, (a, b) => a !== b))),
  companies, extra,
};
writeFileSync(new URL('../map-data.js', import.meta.url),
  `// Generated by promo/tools/build-map.mjs. Do not edit by hand.\nwindow.GAUGE_MAP = ${JSON.stringify(data)};\n`);
console.log(`map-data.js: ${companies.length} companies, ${extra.length} extra signals, ${(JSON.stringify(data).length / 1024).toFixed(0)} KB`);
